### ISSUE TITLE
List PyThaiNLP 1.7

### ISSUE THREAD

**Issue by wannaphongcom** [PyThaiNLP/pythainlp#92]
- [x] train new postag #89 

- [x] rewrite pythainlp.tokenize.pyicu #87 

- [x] Create new sentiment analysis #83

- [x] "newmm" tokenizes white spaces  #65 

- [x] add pythainlp.tag.pos_tag_sents

- [x]  Add converts Thai numbers written in words to digits #94

- [x] Deprecate Python 2 support #107 

- [x]  romanization

- [x]  Thai NER #114

- [x] Docs

**Comment by wannaphongcom** [comment]
Close https://github.com/PyThaiNLP/pythainlp/pull/117/
